### ISSUE TITLE
feat: 대기열 토큰 & 좌석 선택 기능 개선

### ISSUE THREAD

**Issue by dusunax** [EnhancementPlayGround/nest_tdd#28]
## 대기열 토큰 & 좌석 선택 기능 개선
> 작업 기간: 12월 29일 금요일

### Todo
- [x] 다이어그램 작성, 계획
- [x] 대기열 토큰 로직 변경 / 토큰 데이터 (1)대기 시간 (2)상태 추가
- [x] 좌석 선택 기능 / 트랜잭션 구현
- [ ] 기능 동작 확인 필요
- [ ] 테스트 커버리지
![image](https://github.com/EnhancementPlayGround/nest_tdd/assets/94776135/c5fd9a10-d9ef-4bd5-a135-1f7b8b1402eb)

**Comment by dusunax** [comment]
## 개선 내용
### 모듈명/메소드명/route명 변경
- [x] 좌석/예약 모듈 reservations => seats
- [ ] 좌석/예약 route => restful하게 수정
- [ ] 메소드명, 기능 개선과 테스트 코드 작성을 위한 메소드명 변경

### 로직/기능 추가
#### 예약
- [ ] 트랜잭션 구현
- [ ] lock 구현
#### 대기열
- [ ] redis 연결 

## 기능 변경
### 📌 대기열 토큰 구현 방식
#### as is
- (1) 토큰 발급 후, 서버 내 queue와 DB 내 토큰 보관
- (2) 서버 내 queue 관리
<img width="300" alt="image" src="https://github.com/EnhancementPlayGround/nest_tdd/assets/94776135/f92c0ac1-387b-4315-bfdd-7264eb62f2ed">

#### to be
- token으로 entryTime 관리
- redis내 대기열 큐

### 📌 웨이팅룸 구현 방식
#### as is
- (1)서버 내 queue 관리(현재 대기 index 확인) & map(userId와 토큰 매치 확인)

#### to be
- redis 내 웨이팅룸 큐 관리

**Comment by dusunax** [comment]
### 리팩토링 보류로 close합니다
